apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  msg_services: {{ .Values.redis }}
  memcached: {{ .Values.memcached }}
  db_host: {{ .Values.psql }}
