{{- if .Values.hostname }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-{{ .Release.Name }}-{{ .Values.ingress.env }}
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    {{- if eq .Values.ingress.env "staging" }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end }}
    {{- if eq .Values.ingress.env "prod" }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- end }}
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ .Release.Name }}-{{ .Values.ingress.env }}-key
    solvers:
    - http01:
        ingress:
          class: nginx
{{-end }}
